### ISSUE TITLE
Sound sheet id build adjustments

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#103]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/103) by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Build process adds sound sheet id separate from level sheet id in the sheet id bin.

Modify the sheed id builder to have a command option for including _ underscore sheets, rather than doing the hardcoded override for .sound sheets.

In leveldesign, underscore is used for parent sheets that don't need inclusion in the game data, and don't need an id.

In ryzom soundbanks, underscore is often used for master sound sheets (usually context sounds), whereas regular sound sheets (which are randomly picked by the context sounds) have regular names.

**Comment by kaetemi** [comment]
Reversed.
