### ISSUE TITLE
Client connection gets stuck in Probe mode

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#133]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/133) by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Client connection sometimes gets stuck in Probe mode after loading finished, teleportation, and such.

This can be deblocked by suspending and resuming the client process, so seems to be fixable client-side.

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Suspending client causes network packages to stop.

FS code forces server-side entry to Probe mode when no messages arrive from a client after a certain time.

Might be server side then.

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Possibly fixable server-side by putting clienthost in probe mode on the server side when a specified number of empty probe acks is received by the FS and the FS is not in probe mode anymore.

fe_receive_sub.cpp 1088 is probe state

SYSTEM_ACK_PROBE_CODE is only handled when server-side is in probe state

clienthost->setProbeState(); to enter probe state on the service

FS only enters probe when receiving no more incoming messages or when losing too many packages.

**Comment by kaetemi** [comment]
This is still an issue.

**Comment by kaetemi** [comment]
Add a mechanism to simulate forced client-side probe.

**Comment by kaetemi** [comment]
- [x] Fix on client by not sending probe ack when normal packets are received
- [ ] Fix on server by counting empty probe ack packets while in normal state

**Comment by kaetemi** [comment]
Client-side fix works sufficiently.
