### ISSUE TITLE
Strange comportment of OVQT particule editor

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#165]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/165) by yann k (Bitbucket: [yannk2](https://bitbucket.org/yannk2), GitHub: [yannk2](https://github.com/yannk2)).**

----------------------------------------

I use a OVQT Compiled on 21/01/2014 from your website (x86-0.8.0.4059) on a Windows XP VM.
Everything was fine with it for my tests until I close the program and start it again. Now, it looses the links to my assets (it doesn't show no more the .shape included in it nor the textures used). SO I have to reimport them again, and sometimes several times until it shows them correctly. But when I save the .ps file and import it in server, the final object is not visible. It is there, as the collisions are here, but I can't see anything. The first time averything was ok.
I changed nothing in my configuration in the meantime, and the texture and shape files are still in the same place, in a folder alltogether, in my W:/database.
I enclose a copy of my files with this message.

**Comment by ryzom-pipeline** [comment]
**Original comment by yann k (Bitbucket: [yannk2](https://bitbucket.org/yannk2), GitHub: [yannk2](https://github.com/yannk2)).**

----------------------------------------

I have made new tests and I think it is because of a problem in the format of the saved files. As I work with a Windows VM under Linux, I have sometime some issues because of files adresses written in Windows format (with '\'as separations for folder path). I have checked in .pws file, and I saw that the relative path is written like this. And when I put all my files (.pws , .ps andpictures) alltogether in the same folder, I no longer loose the informations. Hope this helps.

**Comment by ryzom-pipeline** [comment]
**Original comment by yann k (Bitbucket: [yannk2](https://bitbucket.org/yannk2), GitHub: [yannk2](https://github.com/yannk2)).**

----------------------------------------

New tests : If I unload ths .pws file and reload it just after, it loads the textures, no problem (with all files in same folder) but if I close OVQT and start it again, it looses the path to files.

**Comment by ryzom-pipeline** [comment]
**Original comment by dfighter1985 (Bitbucket: [dfighter1985](https://bitbucket.org/dfighter1985), GitHub: [dfighter1985](https://github.com/dfighter1985)).**

----------------------------------------

This is how it looks if I have the .ps and .pws files in a separate directory together and the texture files in the data directory of the client ( which is mapped as data directory in my config file ).

![20150201_000002124.jpg](https://bitbucket.org/repo/R9LxXq/images/3749090552-20150201_000002124.jpg)

According to my log file, G_tuyau.png texture is missing.

**Comment by ryzom-pipeline** [comment]
**Original comment by dfighter1985 (Bitbucket: [dfighter1985](https://bitbucket.org/dfighter1985), GitHub: [dfighter1985](https://github.com/dfighter1985)).**

----------------------------------------

To be honest I don't even understand the issue actually.
For the textures to show up, you need them to be in a mapped directory ( data for example ) otherwise the client will not be able to load it.
The same is true for the tools as they use the same library as the client.

**Comment by ryzom-pipeline** [comment]
**Original comment by yann k (Bitbucket: [yannk2](https://bitbucket.org/yannk2), GitHub: [yannk2](https://github.com/yannk2)).**

----------------------------------------

OK, now it seems that the system loose the textures/shapes between two sessions. But it is possible to reimport them eéch time. The only workaround is to have all the files (textures and shapes) in the same folder than the .exe of Ryzom Core Studio.

**Comment by ryzom-pipeline** [comment]
**Original comment by dfighter1985 (Bitbucket: [dfighter1985](https://bitbucket.org/dfighter1985), GitHub: [dfighter1985](https://github.com/dfighter1985)).**

----------------------------------------

I've told you to add them to a mapped directory... You can tell the studio which directories to check for files, those are the mapped directories...

**Comment by ryzom-pipeline** [comment]
**Original comment by yann k (Bitbucket: [yannk2](https://bitbucket.org/yannk2), GitHub: [yannk2](https://github.com/yannk2)).**

----------------------------------------

In the configuration, I have given to RCS the W: drive directly once, it was not functionnal. So I change to W:/database it doesn't work either :/

**Comment by ryzom-pipeline** [comment]
**Original comment by dfighter1985 (Bitbucket: [dfighter1985](https://bitbucket.org/dfighter1985), GitHub: [dfighter1985](https://github.com/dfighter1985)).**

----------------------------------------

Make sure you add it as recursive then :)

**Comment by ryzom-pipeline** [comment]
**Original comment by yann k (Bitbucket: [yannk2](https://bitbucket.org/yannk2), GitHub: [yannk2](https://github.com/yannk2)).**

----------------------------------------

Great ! You got the point !
I was used to add in Tools > Settings the W: drive in the 'Assets database' place, in 'General'but we must add the folder also in :
'General > Search recursive paths'
I have added my W: folder and now all the .ps show the texture right on !

**Comment by kaetemi** [comment]
Review Qt tools.
