### ISSUE TITLE
Implement new movement modes such as jump, dive and swim underwater.

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#17]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/17) by Matt Raykowski (Bitbucket: [Matt Raykowski](https://bitbucket.org/Matt Raykowski), ).**

----------------------------------------

Jumping needs:

* Collision meshes for all IG (currently ground collision meshes and pacs primitives specified in 3d editing software)
* Collision meshes for all trees (currently pacs primitives specified in plant sheets or something)
* Collision meshes for all creatures (currently pacs primitives specified in creature sheets or something)
Cannot do collision meshes directly on a per shape basis because it would be too heavy since creatures are animated and consist of multiple shapes.

* Common code to build collision mesh from zone (on the fly, pre-built may be prohibitively large and pointless)
* A bit on the network that flags which entities the client needs to display using physics instead of pacs (flagged on player entities)
* Optionally a service (or enhancement to GPMS) which randomly selects zones to verify player client physics for a while to detect cheaters
* Client code to interpolate and match local physics of other players' physics characters with server provided values
* Update client animation code to animate characters based on their movement provided by physics to include jumping animation (also requires a method to know if a character is on the ground or not)
And some more stuff too

Jumping animations required:

* Idle_To_Jump
* Jump_To_Idle
* Marche_To_Jump
* Jump_To_Marche
* Course_To_Jump
* Jump_To_Course
* Marche_Arriere_To_Jump
* Jump_To_Marche_Arriere
* Jump (loop)
* Jump_To_Swim_Idle
* Jump_To_Swim_Front
* Jump_To_Swim_Front_Speed
* Jump_To_Swim_Back
* Jump_To_Fall
* Fall (loop) (exists already)
* Fall_To_Idle
* Fall_To_Swim_Idle (exists already)
* Fall_Death
* Jump_To_JumpDeath (when killed mid-air)
* JumpDeath_Loop (falling distance unknown)
* JumpDeath_End (hit ground)

All animations need to take all kinds of equipment into account.

And then a whole bunch of diving animations if you like that too.

**Comment by kaetemi** [comment]
Not practical.
