### ISSUE TITLE
Documentation of Datasheet properties in Georges Editor plugin

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#178]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/178) by yann k (Bitbucket: [yannk2](https://bitbucket.org/yannk2), GitHub: [yannk2](https://github.com/yannk2)).**

----------------------------------------

I thought it would be more efficient to find a way to include the manual of datasheets inside Georges Forms, and to be able to edit the explanations directly in the Georges Editor plugin. Like this, the documentation would be easier to find and increase properly.
The idea would be the display of explanations like these ones in GEQT : https://ryzomcore.atlassian.net/wiki/display/RC/List+of+Brick+Parameters
In an ideal world, this documentation would be included in commentary part of Datasheets, to include them in the xml files, to be sure to always have the correct information.

**Comment by kaetemi** [comment]
Review Qt tools.
