### ISSUE TITLE
Streaming assets from patch server at runtime

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#179]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/179) by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Use the same file loading mechanism as BNP files use, but instead downloading the file from a patch server and reading it from a cache.

Implementation:

Creation of a new package format SNP (Streaming NeL Package), containing the list of filenames, sizes, and a long checksum. The client indexes this the same way as a BNP package. On first request of a file, it is downloaded, and then used in read-only fashion from the cache.

Creation of a snp_make tool, which generates the directory package, and generates the streaming patch server file structure.

Notes:

The patch server stream file structure is to be identical to the cache on the client, and simply consists of the alphanumeric hexadecimal representation of the hash, with the first two bytes separated into folders, as follows.

./stream/01/02/030405060708090a0b0c0d0e0f.lzma

Files server-side are stored lzma-compressed, client side the files are stored uncompressed.

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Add tool to build streamed package, ref #179

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Implementation fixes, ref #179

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Remove some debugging, ref #179

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Implement streamed data download, ref #179

**Comment by kaetemi** [comment]
Merged in with
31e1cd6feb8bfb7302c0552b1e5e6e341d864c8b
b28c9ef8c4d35d2beb3d5b18353a94a0ef53ec9a
