### ISSUE TITLE
API_key_management Crashes AMS

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#184]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/184) by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

Enabling the API_key_management plugin crashes ams

**Comment by ryzom-pipeline** [comment]
**Original comment by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

After latest commit 5297 (2e779e5f8f41) updating plugins error is now


```
#!none

( ! ) Notice: Undefined index: ring in C:\development\ryzom\code\web\private_php\ams\autoload\dblayer.php on line 61
Call Stack
#	Time	Memory	Function	Location
1	0.0010	272816	{main}( )	..\index.php:0
2	0.0170	900664	Plugincache::loadHooks( )	..\index.php:128
3	0.0510	1235984	call_user_func:{C:\development\ryzom\code\web\private_php\ams\autoload\plugincache.php:265} ( )	..\plugincache.php:265
4	0.0510	1236128	api_key_management_hook_load_db( )	..\plugincache.php:265
5	0.0520	1239624	DBLayer->__construct( )	..\API_key_management.php:174

```

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Ring database cannot be opened this way. There must be an associated domain.

Domains may be running different versions of the game, so it may need to be necessary to have the same plugin in multiple versions for different domains?

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Also, similarly how you designed the nel database separation, where you assume the nel db is on a separate box and can be down, the same goes for the ring databases, which are likely to be on the same box as the nel database, as they are used by the game services.

**Comment by ryzom-pipeline** [comment]
**Original comment by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

yes there querycache allows for it to be with ring etc

i think we will need to do some sort of ring loop or something in ams

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

API not a priority

**Comment by ryzom-pipeline** [comment]
**Original comment by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

Agreed, however the bigger issue is the ring stuff, the api itself isnt a problem but we do need to fix the ring items so that it can properly set permissions etc.

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

What ring items?

**Comment by ryzom-pipeline** [comment]
**Original comment by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

Login permissions i think are the only major thing I can think of

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

There are no login permissions for ring to be set specifically. The only thing that needs to happen with the ring databases is that on first login to a domain, the login script creates an entry in the ring domain database, which already just happens in the existing login script which works just fine.

**Comment by ryzom-pipeline** [comment]
**Original comment by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

Doesnt crash anymore, just doesnt work :)

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

For the ring specifics, it should basically use all of the ring databases of the domains the player has permissions for.

**Comment by kaetemi** [comment]
Review AMS.
