### ISSUE TITLE
make all uid's match

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#195]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/195) by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

there is no reason why the shard and ams uid's shouldnt match

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

I already hacked this in.

There's still the weird ticket_user_id database which maps the user id to another user id used for the ticketing system.

I just made it so it creates them all with the same UID, but this table shouldn't even need to exist...

**Comment by kaetemi** [comment]
Review AMS.
