### ISSUE TITLE
AMS domain permissions

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#212]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/212) by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

the only choices are OPEN,DEV,RESTRICTED

it takes OPEN,DEV as a string

**Comment by ryzom-pipeline** [comment]
**Original comment by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

UPDATE `nel`.`permission` SET `AccessPrivilege` = 'DEV,RESTRICTED' WHERE `permission`.`PermissionId` =1;

**Comment by kaetemi** [comment]
Review AMS.
