### ISSUE TITLE
Deprecate the old sound drivers, remove them from compilation.

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#23]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/23) by Matt Raykowski (Bitbucket: [Matt Raykowski](https://bitbucket.org/Matt Raykowski), ).**

----------------------------------------

Remove the FMOD and DSound sound drivers. Make sure that they're not in any of the driver loading code and then remove them from the CMake build paramters so they're no longer able to be compiled without manual intervention.

**Comment by kaetemi** [comment]
No need.
