### ISSUE TITLE
AMS doesn't add user to nel_nel.users table with mysql 5.7.17

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#305]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/305) by Guillaume DUPUY (Bitbucket: [Guillaume DUPUY](https://bitbucket.org/Guillaume DUPUY), ).**

----------------------------------------

When installing AMS, the ams* table are correctly populated, the neltools_users is correctly populated, but no data is inserted in the nel_nel.users table. I can log in fine to the AMS, but no account for the shard is created.
This also happens if you create a new user later, and I can see in the "Syncing" page of the AMS that a "createUser" action for Sid 2 is pending. Clicking on the "manually sync" on the same page does nothing (user is not created).

The bug is not present with mysql 5.5.53 (debian's jessie version)

**Comment by kaetemi** [comment]
Review AMS.
