### ISSUE TITLE
NeL Flare max object has incorrectly flagged "keep 1st size" in many scenes

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#336]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/336) by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

This causes huge flares to show up. Need to investigate why it switched on.

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

This causes huge flares to show up. Need to investigate why it switched on.

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

With wrong option:

![](https://bitbucket.org/repo/R9LxXq/images/2293697890-image.png)
With correct option:

![](https://bitbucket.org/repo/R9LxXq/images/124467244-image.png)
Need to find out which files have the option set wrong…

**Comment by kaetemi** [comment]
https://github.com/kaetemi/ryzomclassic/issues/53
