### ISSUE TITLE
Add getMsgNb method to CBufFIFO

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#402]
Per a todo note in buf_fifo.h:

<pre>
TODO: Add a method getMsgNb() that will return the number of messages in queue.
For acceptable performance, it would need to store the current number instead
of browsing the blocks.
</pre>

If we do not need or want this then we should clear this TODO out of the file before closing the issue.

Original creation date in redmine: 2009/09/03 20:56:26 +0200 by sfb at https://dev.ryzom.com/issues/685

**Comment by kaetemi** [comment]
Cleaning up stale issues.
