### ISSUE TITLE
Split unit test suite into separate modules

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#506]
NeL has a large suite of unit tests but whenever an individual test fails we have no notification as to what area is broken. Splitting the tests into modules related to their library (e.g. NLMISC, NLNET, NL3D, etc) will help us identify failed areas. 

Google code-in task

Original creation date in redmine: 2010/12/03 02:23:33 +0100 by jgeralnik at https://dev.ryzom.com/issues/1209

**Comment by kaetemi** [comment]
Cleaning up stale issues.
