### ISSUE TITLE
Merge in Game Share Unit Test from GCI Task

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#508]
http://socghop.appspot.com/gci/task/show/google/gci2010/worldforge/t128955418827 - this was my GCI task. I attach file with tar of unit test folder and patch file

Original creation date in redmine: 2010/12/09 22:15:09 +0100 by peneon at https://dev.ryzom.com/issues/1211

**Comment by ryzom-pipeline** [comment]
[game_share_unit_test.tar.gz.tar.gz](https://github.com/ryzom/ryzomcore/files/3891269/game_share_unit_test.tar.gz.tar.gz)

**Comment by kaetemi** [comment]
These tests look useless, to be honest.
