### ISSUE TITLE
Merge in Server Share Unit Test from GCI Task

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#512]
Unit tests for server_share.

Original creation date in redmine: 2010/12/22 21:15:41 +0100 by jgeralnik at https://dev.ryzom.com/issues/1220

**Comment by ryzom-pipeline** [comment]
[server_share_patch.zip](https://github.com/ryzom/ryzomcore/files/3891274/server_share_patch.zip)

**Comment by kaetemi** [comment]
Ok, this is also useless.
