### ISSUE TITLE
VS2012?

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#53]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/53) by Anonymous.**

----------------------------------------

Hey guys you have putted compatibility to compile with Visual studio 2012?

**Comment by ryzom-pipeline** [comment]
**Original comment by Matt Raykowski (Bitbucket: [Matt Raykowski](https://bitbucket.org/Matt Raykowski), ).**

----------------------------------------

There has been some effort around this, particularly thanks to @StudioEtrange . Have you attempted to build and run into some problems?

**Comment by ryzom-pipeline** [comment]
**Original comment by S (Bitbucket: [S](https://bitbucket.org/S), GitHub: [S](https://github.com/S)).**

----------------------------------------

Daggra : I am still working on VS2012, maybe good for septembre
(actually nmake, with VS2012 Update 3 and WinSDK8)

**Comment by ryzom-pipeline** [comment]
**Original comment by Anonymous.**

----------------------------------------

yes it have a lot of crashes and errors but it's for the externals i think

**Comment by ryzom-pipeline** [comment]
**Original comment by S (Bitbucket: [S](https://bitbucket.org/S), GitHub: [S](https://github.com/S)).**

----------------------------------------

This sunday I will release scripts that compile on VS2012 (and other) I will need some help to test ;)

**Comment by ryzom-pipeline** [comment]
**Original comment by S (Bitbucket: [S](https://bitbucket.org/S), GitHub: [S](https://github.com/S)).**

----------------------------------------

Hello Dragga

Could you test the windows capabilities of this tool ?

https://bitbucket.org/StudioEtrange/ryzomcore-script

I made this tool to manage and build ryzomcore source on windows and ubuntu.
**This is a early test version.** 

Features

* External dependencies source code management and build system

* Ryzomcore source code management and build system

* Command Line based for windows ans Ubuntu

* Provide support of nmake, gnu make and ninja build tools

* Support x64 and x86

* Support of fast build with multicpu compilation (via Ninja)

* Support PCH compilation

* Generation of solution project for Visual Studio

**Comment by ryzom-pipeline** [comment]
**Original comment by Jan Boon (Bitbucket: [Jan Boon](https://bitbucket.org/Jan Boon), ).**

----------------------------------------

Issue inactive

**Comment by kaetemi** [comment]
Outdated.
