### ISSUE TITLE
Support for Nvidia PerfHUD

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#579]
Here is a patch that allows you to use nvidia perfhud with D3D on ryzom. ( https://developer.nvidia.com/nvidia-perfhud )

Note: _DeviceInterface->Reset caused it to crash when using perfhud, should we be resetting normally?

Original creation date in redmine: 2012/10/29 01:49:54 +0100 by Botanic at https://dev.ryzom.com/issues/1505

**Comment by ryzom-pipeline** [comment]
![image](https://user-images.githubusercontent.com/16483016/69622264-95e42480-107b-11ea-9275-dd1e5548f28b.png)
[2691.zip](https://github.com/ryzom/ryzomcore/files/3891352/2691.zip)

**Comment by kaetemi** [comment]
Cleaning up stale issues.
