### ISSUE TITLE
server src not found in code\ryzom\server

### ISSUE THREAD

**Issue by Argez** [ryzom/ryzomcore#587]
Good morning,

I have been trying to compile the server using all the steps described in the documentation, however the following .exe is not achieved

ryzom_admin_service.exe
ryzom_backup_service.exe
ryzom_entities_game_service.exe
ryzom_gpm_service.exe
ryzom_ios_service.exe
ryzom_naming_service.exe
ryzom_welcome_service.exe
ryzom_tick_service.exe
ryzom_mirror_service.exe
ryzom_ai_service.exe
ryzom_mail_forum_service.exe
ryzom_shard_unifier_service.exe
ryzom_frontend_service
ryzom_session_browser_service.exe
ryzom_logger_service.exe
ryzom_dynamic_scenario_service.exe

I was checking and what repository clone does not have the src folder in code \ ryzom \ server. Where can I get those files to compile properly?

**Comment by kaetemi** [comment]
The develop branch is broken. I'm working to restore all functionality in the ryzomclassic branch.

**Comment by kaetemi** [comment]
No ETA. Feel free to dabble in it yourself. Hopping between shards is broken, and the Ryzom Core leveldesign dataset is missing some essentials to have a usable R² shard.

**Comment by Argez** [comment]
Good morning. thanks for the info.

In these days I have been testing and debugging the code and I already
solved a fault and it was that from the client I was sending an id of
a continent that does not exist and then I made the change so that it
would always point towards newbieland when creating the character. Now
the world starts me and I can normally enter the level and continent.

What does not work for me now is the button of the world editor on the
client, since clicking the client is loading and then closes.

I have a question. Do you know what services and settings are
responsible for controlling the world editor?

Greetings and attentive to your comments.

------------------------------

**Comment by kaetemi** [comment]
The world editor is the part which depends on switching between server,
it's the part that's broken.

You need session browser service on a port 1000 above the frontend service
port. And run a second shard in Ring mode.

But the confirmation network message from the server for the client to
finalize the teleport is not getting sent.

**Comment by Argez** [comment]
Good Morning.

Thanks for the information, I will continue testing with the ring
server to see if I can get the solution to work.

If in doubt, can I continue consulting?


Greetings and attentive to your comments.

**Comment by kaetemi** [comment]
Included on **core4** branch.
