### ISSUE TITLE
Important. Contents of `code` moving to root folder

### ISSUE THREAD

**Issue by kaetemi** [ryzom/ryzomcore#593]
Hi all,

**To simplify environment setup and folder structure, I'm moving the contents of the useless `code` folder to the root of the repository.** This is in effect **now** on the develop branch.

This change will merge into your own branches without issue, if your branch is up to date with develop. Moved files are correctly tracked by git. You'll just need to move any files that you may have added in your branch, that don't exist in the develop branch, manually after merging, as they might remain in the old folder structure. The following sequence should give you a conflict free merge.

```
git merge origin/feature/pre-code-move
git reset --hard
git merge origin/feature/post-code-move
git add *
git commit
git merge origin/develop
```

Similarly, the contents of `leveldesign` are moved to the root of the reference leveldesign repository.
For a simplified build pipeline experience, all repositories are now simply expected under the virtual `R:` drive, instead of several different drives.

**Also!** The full pipeline configuration to build the complete landscape data has been added into the Ryzom Core leveldesign repository. Enjoy. ;)
You **will** need to redownload the ryzomcore_graphics repository, as the repository max files have all been adjusted to follow the new path structure. Do not pull from an existing copy, as some history has been cleaned out to save on LFS space.

An updated reference project folder structure is as follows:
* **R:**: Project root
  * build: Contains your build folders, contents depends on your code toolchains
    * dev_x64
    * fv_x64
    * server_gcc
    * server_x64
    * *etc...*
  * **code**: The code repository
    * nel
    * ryzom
    * *etc...*
  * distribution: Your installers and archives of tools for artists and pipeline
  * external: Your external dependencies
  * **graphics**: The graphics repository *(previously W:\\database)*
    * landscape
    * sfx
    * stuff
    * *etc...*
  * **leveldesign**: The leveldesign repository *(previously L:\\leveldesign and L:\\)*
    * DFN
    * game_elem
    * primitives
    * translation
    * *etc...*
  * **patchman**: Your configuration files for the server patch manager *(see patchman_cfg)*
    * admin_install
    * cfg
    * default
    * *etc...*
  * **pipeline**: Output from build_gamedata *(previously T:\\)*
    * bridge_server
    * client_patch
    * export
    * worldedit
    * *etc...*
  * **sound**: Your sound repository
    * DFN
    * animations
    * samplebanks
    * *etc...*

**Comment by kervala** [comment]
Good idea, the build scripts will have to be modified accordingly :)

**Comment by kaetemi** [comment]
Yep. Also hoping to make a single zip with all the repositories and dependencies in place, fully pre-built, so someone who wants to get started can just download, run, and work on the whole thing.

**Comment by kaetemi** [comment]
`feature/code-to-root-atys` branch for your convenience...
