### ISSUE TITLE
 Error in world_editor.exe editing newbieland.world

### ISSUE THREAD

**Issue by Argez** [ryzom/ryzomcore#599]
good morning.

The technology of the world editor seems very interesting to me

I am modifying the newbieland.worldedit continent. When I press save, 
Changes if saved to newbieland.worldedit file. I am not generating the newbieland.land file. In log.log I am seeing that these errors are generated:

2020/04/08 07:47:40 DBG 1b44 world_editor.exe config_file.cpp 397 NLMISC :: CConfigFile :: reparse: CF: Adding config file 'R: /code/ryzom/tools/leveldesign/install//world_editor_plugin.cfg 'in the config file
2020/04/08 07:47:53 WRN 1b44 world_editor.exe path.cpp 711 NLMISC :: CFileContainer :: setCurrentPath: Cannot change current path to '' (current path is' R: / code / ryzom / tools / leveldesign / install / world_editor_continents') res: -1 errno: 22 (Invalid argument)
2020/04/08 07:47:55 WRN 1b44 world_editor.exe world_editor.cpp 1048 getTextureFile: fp_8ao doesn't exist in tga or in png
2020/04/08 07:47:55 WRN 1b44 world_editor.exe file.cpp 271 NLMISC :: CIFile :: open: Failed to open file 'fp_8ao', error 2: No such file or directory
2020/04/08 07:47:55 WRN 1b44 world_editor.exe builder_zone.cpp 355 CDataBase :: loadBitmap: Bitmap not found: fp_8ao
2020/04/08 07:47:55 WRN 1b44 world_editor.exe world_editor.cpp 1048 getTextureFile: frontiere-1 doesn't exist in tga or in png
2020/04/08 07:47:55 WRN 1b44 world_editor.exe file.cpp 271 NLMISC :: CIFile :: open: Failed to open file 'frontiere-1', error 2: No such file or directory
2020/04/08 07:47:55 WRN 1b44 world_editor.exe builder_zone.cpp 355 CDataBase :: loadBitmap: Bitmap not found: frontiere-1
2020/04/08 07:47:56 WRN 1b44 world_editor.exe world_editor.cpp 1048 getTextureFile: jungle-0 doesn't exist in tga or in png
2020/04/08 07:47:56 WRN 1b44 world_editor.exe file.cpp 271 NLMISC :: CIFile :: open: Failed to open file 'jungle-0', error 2: No such file or directory
2020/04/08 07:47:56 WRN 1b44 world_editor.exe builder_zone.cpp 355 CDataBase :: loadBitmap: Bitmap not found: jungle-0

What to do to fix these and errors and also to generate the newbieland.land file

I am currently running:
world_editor.exe from path R: \ code \ ryzom \ tools \ leveldesign \ install and loading newbieland from path R: \ code \ ryzom \ tools \ leveldesign \ install \ world_editor_continents

greetings and attentive to your comments.

**Comment by Argez** [comment]
Good morning. It works for me.

I have been doing tests with the world editor creating and editing continents, and I have these questions:

1.-When creating a continent and editing it, are there already predefined designs, what must be done to be able to add custom relief designs?
2.-How big can a continent be so that it can work well on the server and clients?
3.-In what way can a dungeon be created.
4.-I was seeing that in many parts of the code and in the world editor they make references to pets. What are pets for in the game?

greetings and attentive to your comments.

**Comment by kaetemi** [comment]
1. Create patch zones in max
2. Big
3. Can fully make in max, or make square tileable zones in max and assemble in world editor
4. Mektoubs storage and mounts

**Comment by Argez** [comment]
Is it possible to create pets that follow the player?

**Comment by kaetemi** [comment]
Storage pets can follow the player, so sure, why not?

**Comment by Argez** [comment]
Hello, thank you very much for the information.

**Comment by Argez** [comment]
good morning

Right now I have the newbieland and I have created a testland to test.

How can I teleport a character from Newbieland to Testland?

I've been seeing that in world editor there is something called teleport_triggers and teleport_destination, however I don't see documentation on how to configure it

greetings and attentive to your comments.

**Comment by kaetemi** [comment]
For testing, set your character to have :DEV: permissions in the account database.
Then you can issue /a Position 123,-123 to go there.

**Comment by kaetemi** [comment]
Check R:\code\ryzom\common\data_leveldesign\leveldesign\world_editor_files\class_doc for leveldesign doc.

**Comment by Argez** [comment]
Hi. Thank you very much, I already saw the documentation in the path you passed me. The Dev configuration of the character will be useful to me

**Comment by Argez** [comment]
Good morning.
I did everything you told me to do tests and if it worked. The land I made already runs well for me.
