### ISSUE TITLE
Dev build crashes on connection for da890311bb02133c10cf40ceb85c4924f876eb71

### ISSUE THREAD

**Issue by planetmaker** [ryzom/ryzomcore#611]
The dev build does not start up properly and crashes after getting login credentials and trying to connect to the server.

It seems that the included automatic patching process removes the execute flag from the files, and especially crash_report - so that the command subsequently fails to report the crash:

[planetmaker:~/ryzom/ryzom-core] [base] d0068265f 10s 141 ± git checkout origin/HEAD
[planetmaker:~/ryzom/ryzom-core] [base] da890311b ± git log
commit da890311bb02133c10cf40ceb85c4924f876eb71 (HEAD, origin/develop, origin/HEAD, develop)

(...)

[planetmaker:~/ryzom/ryzom-core] [base] da890311b 9s 141 ± cd ../dev-build/
[planetmaker:~/ryzom/dev-build] [base] $ ../builddev.sh 

(...)

[100%] Linking CXX executable ../../../bin/ryzom_client_dev
[100%] Built target ryzom_client
⌂73% [planetmaker:~/ryzom/dev-build] [base] 6m46s $ cp bin/* ~/ryzom/bin
[planetmaker:~/ryzom/dev-build] [base] 4s $ cd ~/ryzom/bin
[planetmaker:~/ryzom/bin] [base] $ ./ryzom_client_dev 
ERR 1f025880 load_form.h 211 loadForm ryzom_client_dev : loadForm(): Exception during reading the packed file and can't reconstruct them (The packed sheet version in stream is different of the code)
Dumping call stack :
0 : /home/planetmaker/ryzom/dev-build/lib/libnelmisc.so.1(_ZN6NLMISC12getCallStackERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x41) [0x7f3f20440f91]
1 : /home/planetmaker/ryzom/dev-build/lib/libnelmisc.so.1(_ZN6NLMISC18getCallStackAndLogERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x32) [0x7f3f20441112]
2 : /home/planetmaker/ryzom/dev-build/lib/libnelmisc.so.1(_ZN6NLMISC4CLog13displayStringEPKc+0x306) [0x7f3f204a8006]
3 : /home/planetmaker/ryzom/dev-build/lib/libnelmisc.so.1(_ZN6NLMISC4CLog9displayNLEPKcz+0x125) [0x7f3f204a84b5]
4 : /home/planetmaker/ryzom/dev-build/lib/libnelmisc.so.1(_ZN6NLMISC12nlFatalErrorEPKcz+0x14a) [0x7f3f20440d3a]
5 : /home/planetmaker/ryzom/bin/ryzom_client_dev(_Z8loadFormI18CSheetManagerEntryEvRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EERKS7_RSt3mapIN6NLMISC8CSheetIdET_St4lessISG_ESaISt4pairIKSG_SH_EEEbb+0x48be) [0xb5af5e]
6 : /home/planetmaker/ryzom/bin/ryzom_client_dev(_ZN13CSheetManager12loadAllSheetERN6NLMISC17IProgressCallbackEbbbbPKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS9_EE+0x698) [0xb4e4f8]
7 : /home/planetmaker/ryzom/bin/ryzom_client_dev(_ZN13CSheetManager4loadERN6NLMISC17IProgressCallbackEbbb+0x20) [0xb4f040]
8 : /home/planetmaker/ryzom/bin/ryzom_client_dev(_Z11postlogInitv+0xa4e) [0x9b86be]
9 : /home/planetmaker/ryzom/bin/ryzom_client_dev(main+0xdf6) [0x775066]
10 : /lib64/libc.so.6(__libc_start_main+0xf2) [0x7f3f20122042]
11 : /home/planetmaker/ryzom/bin/ryzom_client_dev(_start+0x2e) [0x7c1d4e]
-------------------------------

Log with no filter:
-------------------------------
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_forest2.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_forest.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_forest.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_jungle_pz.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_jungle_pz.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_jungle_maps.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_jungle_maps.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_jungle2.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_jungle2.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_jungle.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_jungle.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_lakes_pz.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_lakes_pz.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_lakes_maps.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_lakes_maps.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_lakes2.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_lakes2.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_lakes.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_lakes.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_roots_pz.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_roots_pz.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_roots_maps.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_roots_maps.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_roots2.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_roots2.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_roots.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_roots.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : r2_misc.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for r2_misc.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : examples.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for examples.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : user.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 1707 : Can't find file category for user.bnp:
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : exedll_win64_.ref
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : exedll_win32_.ref
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : exedll_linux64.bnp
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : exedll_linux64_.ref
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : exedll_linux32_.ref
2020/05/11 16:46:04 ryzom_client_dev WRN b89d2700 login_patch.cpp 2222 : exedll_osx_.ref
2020/05/11 16:46:04 ryzom_client_dev INF 1f025880 sound_manager.cpp 1354 : The current weather setup '' is unknown !
2020/05/11 16:46:04 ryzom_client_dev INF 1f025880 clustered_sound.cpp 220 : CClusteredSound::update : no scene specified !
2020/05/11 16:46:05 ryzom_client_dev INF 1f025880 item_group_manager.cpp 355 : Starting migration
2020/05/11 16:46:05 ryzom_client_dev INF 1f025880 item_group_manager.cpp 358 : Item group migration from old system to new system is done !
2020/05/11 16:46:07 ryzom_client_dev INF b91d3700 login.cpp 271 : Deleting cached files
2020/05/11 16:46:09 ryzom_client_dev INF 1f025880 client.cpp 366 : Login of Ryzom success
2020/05/11 16:46:09 ryzom_client_dev INF 1f025880 client.cpp 369 : Post-Login Init of Ryzom...
2020/05/11 16:46:09 ryzom_client_dev WRN 1f025880 path.cpp 585 : PATH: File (file_index.cfg) not found (file_index.cfg)
2020/05/11 16:46:09 ryzom_client_dev WRN 1f025880 ligo_config.cpp 262 : Can't find index file 'file_index.cfg' in search path, no file index available for alias
2020/05/11 16:46:09 ryzom_client_dev DBG 1f025880 sheet_id.cpp 436 : Finished loading sheet_id.bin: 124925 entries read
2020/05/11 16:46:09 ryzom_client_dev INF 1f025880 common.cpp 918 : Exception will be launched: The packed sheet version in stream is different of the code
2020/05/11 16:46:09 ryzom_client_dev ERR 1f025880 load_form.h 211 : loadForm(): Exception during reading the packed file and can't reconstruct them (The packed sheet version in stream is different of the code)
-------------------------------
User Crash Callback:
-------------------------------
UserId: 4294967295
HomeId: 0
ShardId: 0
On a Mainland Shard
Application: ryzom_live
No user entity information
ViewPosition: 0.00 0.00 0.00
Time in game: 0h 27min 0sec
LocalTime: 2020/05/11 16:46:09
ServerTick: 0
ConnectState: NotInitialised
LocalAddress: :0 (::)
Language: Deutsch
ClientVersion: DEV 3.5.0.0 (2020-05-11 16:38:25)
PatchVersion: 831
Client is online
NumServerHOP: 0
NumFarTP: 0
NumReselectPerso: 0
Connection Events: 
OpenAL
Source size: 32
Effects size: 0
-------------------------------
sh: crash_report: Kommando nicht gefunden.

**Comment by nimetu** [comment]
You cannot use live ryzom data for client compiled using develop branch. You need to use atys branch for that.
Packed sheets are different. It says so in error log.
