### ISSUE TITLE
 Client closes unexpectedly while character walks

### ISSUE THREAD

**Issue by Argez** [ryzom/ryzomcore#613]
Good morning I have a problem.

I already have the fauna configured and it is working for me. However, I have noticed the following problems to which I cannot find a solution:

1.- The client suddenly closes and then in a nel_report file the following error message is displayed: The thread attempted to read from or write to a virtual address for which it does not have the appropriate access.

2.-The client stops slightly and a small window is displayed that says: "please wait"

What can be the cause of these errors?

greetings and attentive to your comments.

**Comment by nimetu** [comment]
Unknown.

I do know that there is issue with sound under macOS.

**Comment by Argez** [comment]
Now I am running it on windows, I don't have the sounds. That's where I get the error

**Comment by Argez** [comment]
I think that error started to appear after I configured the fauna
