### ISSUE TITLE
Create a Flatpak version of Ryzom

### ISSUE THREAD

**Issue by FinixFighter** [ryzom/ryzomcore#614]
Hi! I'd like so much to see a Flatpak version of this game. Moreover, I think it would be easier to find the game if it appears in the software manager of some Linux distro (like the Linux Mint one for example). The deb version would be also amazing! 
Are there any progresses/plans in these directions?

**Comment by nimetu** [comment]
Something to consider is that game is 1.7GiB packed / 8GiB unpacked. Live version also updates itself (data and executable). For live game, only dependency is openal package. Installer requires qt5.

AppImage/Flatpak/Snap/deb package for live game would just be installer which currently downloads the tar and unpacks it.

**Comment by FinixFighter** [comment]
> Something to consider is that game is 1.7GiB packed / 8GiB unpacked. Live version also updates itself (data and executable). For live game, only dependency is openal package. Installer requires qt5.
> 
> AppImage/Flatpak/Snap/deb package for live game would just be installer which currently downloads the tar and unpacks it.

This could sound strange, but for a lot of people it's not easy to know what to do for installing the game. Having a package would be more intuitive for some people.

**Comment by kaetemi** [comment]
https://docs.flatpak.org/en/latest/single-file-bundles.html

Can we perhaps build a Flatpak with just the interface.bnp, let the patcher download the rest of the BNPs into a user folder somewhere, and also allow the patcher to update the Flatpak bundle itself?

**Comment by kaetemi** [comment]
SteamRT Scout with GCC9 builds seems portable enough. Closing this for now, unless there's a real need for it.
