### ISSUE TITLE
Please try to avoid the trend to create new avatars in a new account

### ISSUE THREAD

**Issue by luffah** [ryzom/ryzomcore#615]
Hello,

  many players in Ryzom create a new account only to have a new avatar that assist the main one for digging or healing.

  That is cheating. but yes i guess some reason why people does that :
-  digging is so long to do alone, and almost impossible in prime roots
-  healing level is impossible to raise alone
-  having a healer rescuer is convenient in dangerous zone

  Too, i guess the aim of these constraints are to encourage people to play together. But actually, that encourage people using alternative account to have an assistant; using many computers or a powerful computer to launch many Ryzom sessions (not really eco-friendly ^^).

  Some things that could be done (bad & good ideas mixed):
1. avoid Ryzom installer to launch multiple Ryzom session
2. (if no 1.) allow to play with another avatar with the same account
3. add possibility to do things restricted things with an alternative avatar like sharing objects (similarly of what you can do with a guild bag)
4. add possibility of automatic (but with low effect) care-planning either with an alternative avatar or with something similar to a crystallized spell (or hiring a NPC) or a damn cheated item (that will be for example too heavy to balance the gain)
5. add possibility to work/assist/team with NPC as healer
6. allow to hire NPC mercenaries or bandits for exploration quests and kitins invasion

**Comment by nimetu** [comment]
Keep live game content issues in the forum please.
