### ISSUE TITLE
Poor handling of rotation while right mouse button is pressed down.

### ISSUE THREAD

**Issue by JontomXire** [ryzom/ryzomcore#616]
OS: Linux (Steam).

This issue is twofold but I believe the fix is the same.

### Behaviour 1:
**Steps to reproduce:**

Move the mouse to the far right or left of the screen.
Press and hold the right mouse button.
Gently move the mouse.

**Expected behaviour:**

The camera rotates smoothly.

**Actual behaviour:**

The camera jumps in an extremely disorientating fashion.

**Suspected cause:**

The camera position is being calculated using a delta relative to the screen centre even though the cursor was not in the middle when the mouse button was pressed and held.

### Behaviour 2:
**Steps to reproduce:**

Press and hold the right mouse button.
Move the mouse continuously in one direction, left to right or right to left.

**Expected behaviour:**

The camera rotates smoothly and continuously.

**Actual behaviour:**

The camera rotates smoothly for a while and then stops rotating any further.

**Suspected cause:**

The cursor, which is hidden, reaches the edge of the screen.

**Possible fix:**

I suspect the fix for both of these is to programmatically move the mouse pointer to the centre of the screen, when the mouse button is first pressed, and when after the rotation delta is calculated on each frame/mouse move event.

It would also improve behaviour (if not already implemented) if the mouse position when the right mouse button was pressed and the cursor was hidden, was restored when the mouse button is released.

**Comment by nimetu** [comment]
Wayland or X11 on linux? It works fine on X11, I do not have Wayland to test.

Mouse cursor is moved into center and delta is used.

There is tablet/trackpad mode option in ingame config which will prevent that erratic movement (movement does stop at border tho).

**Comment by JontomXire** [comment]
X11 on Linux.

Stopping at the border is irritating. I was checking out a structure for openings by circling around it and kept having to release and repress the right mouse button. And if I forgot to move the mouse to the middle after releasing...

I am trying to build and run the client to help debug/fix the issue. I can build the client but when I run it keeps complaining that it cannot find ryzom.ttf.

**Comment by JontomXire** [comment]
I forked the repo, checked out the Atrys branch, built, and ran against a standard non-Steam install. This bug is not present.

This bug seems to only be present in the Steam version which I will now uninstall. It might be a side effect of the SteamOS graphics framework/engine.

**Comment by JontomXire** [comment]
With experimentation I have found that this issue only occurs when you invert the mouse. I used to play flight simulators, so I like to "pull back on the stick" to look up.

**Comment by kaetemi** [comment]
9532fc3a81ba2bc8f499af3cbcaf8d5e85a98d0b
