### ISSUE TITLE
Deposit tracking (100% success) says resources are within 1 metre, prospecting (range 5 metres, 100% success) says not.

### ISSUE THREAD

**Issue by JontomXire** [ryzom/ryzomcore#617]
I used my fledgling deposit tracking skill and found a location where the skill tells me that resources are within 1 metre.

I use my fledgling prospecting skill, well not quite fledgling as I added 5M range and extra compensation to get 100% success, and it tells me there are no resources.

I have screenshots.
![found_resource](https://user-images.githubusercontent.com/5786247/92332188-aea25180-f073-11ea-8af6-c4c2e9f562a8.png)
![no_resources](https://user-images.githubusercontent.com/5786247/92332189-b06c1500-f073-11ea-831c-494288dff400.png)

**Comment by nimetu** [comment]
Tracking leads you to the deposit area. Area is described (on server side) as polygon where resources are present.
Individual resource spawn is procedurically checked at prospect time.  Server does not know where resource spawns before user uses prospect.

The result you got is correct.

**Comment by JontomXire** [comment]
The skill description as given by the quest giver for tracking is that it tells you where to prospect. If tracking tells you that you are within 1 metre, and prospecting with a range of 5 metres fails to find anything, then something is broken somewhere even if it is only the description of the skill or the message output by the skill!

The text output from tracking states UNEQUIVOCALLY that there are resources within 1 metre. Not that the character is within 1 metre of the general vague area within which there are resources.

I would suggest that you change the text output of the tracking skill to something like "You are now within the general area where there are resources."
