### ISSUE TITLE
Cant build on manjaro linux

### ISSUE THREAD

**Issue by LinuxDonald** [ryzom/ryzomcore#618]
Hey guys im trying to update the aur package for Arch Linux/Manjaro.
But if i want to build i get that error:

[  8%] Building CXX object nel/src/misc/CMakeFiles/nelmisc.dir/system_info.cpp.o
/home/schatzi/Downloads/ryzom-hg/src/ryzomcore/code/nel/src/misc/system_info.cpp:182:11: fatal error: sys/sysctl.h: No such file or directory
  182 | # include <sys/sysctl.h>
      |           ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [nel/src/misc/CMakeFiles/nelmisc.dir/build.make:1265: nel/src/misc/CMakeFiles/nelmisc.dir/system_info.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3504: nel/src/misc/CMakeFiles/nelmisc.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

**Comment by nimetu** [comment]
you are missing kernel headers. nothing to do with ryzom

**Comment by LinuxDonald** [comment]
On Arch linux the include path is maybe wrong? usr/lib/modules/5.8.11-arch1-1/build/include/linux/sysctl.h

**Comment by nimetu** [comment]
Unless you script completely replaces include directories, you do not need to specify system include dirs.

**Comment by LinuxDonald** [comment]
https://lwn.net/Articles/795164/

/sys/sysctl.h is deprecated.

glibc don't have this include file anymore.

**Comment by nimetu** [comment]
Thanks. I fixed it in develop branch. Atys branch is a bit behind and I dont know when develop is merged into atys.

If aur package supports patches, then you need to apply the patch into atys branch (simply delete that include line).

**Comment by LinuxDonald** [comment]
Thank you
