### ISSUE TITLE
Support Lua 5.4

### ISSUE THREAD

**Issue by kaetemi** [ryzom/ryzomcore#620]
`Lua 5.4 was released on 29 Jun 2020.`

**Comment by mlcdev** [comment]
Can be closed now? Should be in https://github.com/ryzom/ryzomcore/commit/1f856ecd8ead5b3f7933bc94c77e9b7c77399197

**Comment by kaetemi** [comment]
Still missing some stuff for Windows.

>

**Comment by kaetemi** [comment]
Seems good now.
