### ISSUE TITLE
web_on.bat per instructions will not find correct files

### ISSUE THREAD

**Issue by acidmanifesto** [ryzom/ryzomcore#653]
Per instructions following here: https://wiki.ryzom.dev/development/quickstart_windows
I get this message for access log and error log:
![image](https://user-images.githubusercontent.com/16887899/143690404-ce8e7626-043a-437c-a209-f3e7c6ab71d4.png)

but mariadb phpadmin and ngnix loads up fine with no issues:
![image](https://user-images.githubusercontent.com/16887899/143690432-6cb26926-914d-40a5-beb0-d41e2536a730.png)
But when attempting to  to goto the local site i get the following message and can not continue any further:
![image](https://user-images.githubusercontent.com/16887899/143690452-dee57903-cc45-4a63-b7fa-f0e58132a41b.png)

**Comment by kaetemi** [comment]
What's your full path where you extracted everything?

There may still be issues with spaces in paths. Also, very long paths will give errors under Windows.

**Comment by acidmanifesto** [comment]
Path is d:\ryzomcore\

**Comment by kaetemi** [comment]
Which version of Windows?

**Comment by acidmanifesto** [comment]
Windows 10 x64 pro

**Comment by kaetemi** [comment]
Any visible errors if you run web_on.bat from command line?

**Comment by acidmanifesto** [comment]
None that i am able to scroll and see.
Redownloaded the project files 3 times in total. Still the same thing. Running it as a local. No fancy antivirus or firwall besides windows defender if that helps any.

**Comment by kaetemi** [comment]
What's the contents of external/nginx/conf/nginx.conf?

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/146792723-6bd2af85-1246-4367-8376-74552c53677d.png)
Contents is blank

**Comment by kaetemi** [comment]
Example contents should be
```
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       9042;
        server_name  localhost;
        root         Y:/ryzomcore4/code/web/public_php;
        index        index.php index.html index.htm;
        location ~ /\.ht {
            deny  all;
        }
        location /phpmyadmin {
            root  Y:/ryzomcore4/external;
            location ~ ^/phpmyadmin/(.+\.php)$ {
                fastcgi_pass   127.0.0.1:9041;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
                include        fastcgi_params;
            }
        }
        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9041;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
    }
}
```
(With the appropriate paths.)

**Comment by kaetemi** [comment]
This is generated by external/nginx_setup.bat

**Comment by acidmanifesto** [comment]
After running that nginx_setup.bat i do end up with the follow, i did not modify anything:
```worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       9042;
        server_name  localhost;
        root         /code/web/public_php;
        index        index.php index.html index.htm;
        location ~ /\.ht {
            deny  all;
        }
        location /phpmyadmin {
            root  /external;
            location ~ ^/phpmyadmin/(.+\.php)$ {
                fastcgi_pass   127.0.0.1:9041;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
                include        fastcgi_params;
            }
        }
        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9041;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
    }
}
```

However, even after doing that and restarting everything. I still get the error on the browser.
![image](https://user-images.githubusercontent.com/16887899/146979516-667b02cf-e38c-47d9-8b0c-65595d0e3d4a.png)

**Comment by kaetemi** [comment]
Yes, your `root` entries are not getting filled in.

**Comment by acidmanifesto** [comment]
> Yes, your `root` entries are not getting filled in.

Any way to correct that?

**Comment by kaetemi** [comment]
Does your Windows installation have PowerShell installed?

**Comment by acidmanifesto** [comment]
currently it has the powershell that is built in to windows 10 pro.
![image](https://user-images.githubusercontent.com/16887899/149241182-a0bb065b-20f6-4b44-8f62-e7e8792cae57.png)

**Comment by kaetemi** [comment]
Ok. I'm rewriting the quick start scripts. Should be fixed on next release.

**Comment by kaetemi** [comment]
This should be fixed now. Reopen if it still happens.
