### ISSUE TITLE
Add a little jump animation for show — Sample case for Blender animation export

### ISSUE THREAD

**Issue by ulukyn** [ryzom/ryzomcore#658]
Idea from https://app.ryzom.com/app_forum/index.php?page=topic/view/32034/2

**Comment by kaetemi** [comment]
Are you hiring an animator to create the animations?

**Comment by kaetemi** [comment]
If not, then this is moot.

**Comment by Zatalyz** [comment]
About animation, if it is created with blender, can you implement it on game ?

**Comment by ulukyn** [comment]
I have no idea how export an animation to be used on Ryzom, but we can try

**Comment by kaetemi** [comment]
It's possible if you can import the animation skeleton from the max files without flipping any pivot points...

**Comment by kaetemi** [comment]
At minimum two or three animations...
Idle -> jump -> idle
Run/walk -> jump -> run/walk

The blending of jumping while running will look funny, though, since the animation blending in Ryzom is a bit rudimentary... (In fact, most of the specific blending animations are not even implemented currently! :( )

**Comment by kaetemi** [comment]
Or a bit fancier...
Run/walk -> jump -> swim

And some useless ones...
backwards -> jump -> backwards
strafe -> jump -> strafe

**Comment by kaetemi** [comment]
Skeleton can be exported straight from the Blender file into NeL, so it can be checked whether it's ok. Maybe even retargeted to the proper skeleton at NeL level with some work if there's a mismatch.

No animation export from Blender files yet, since nobody has made any animations for the game in Blender.

**Comment by kaetemi** [comment]
If we make a skel2blend tool to definitely get the right skeleton in there, then our chances will be better...

**Comment by Zatalyz** [comment]
So it is not only about "make an animation". Finding animators working with Blender is possible. Finding animators able to use Ryzom specific tools will be almost impossible. Perhaps you should focus on a Blender to NeL tool beforehand try to solve this ?

**Comment by kaetemi** [comment]
We already have a Blender to NeL tool already that works for shapes and skeletons.

We do not have any actual Blender content, so it is entirely moot to make any more tools for that scenario at this point.

Finding animators who can work 3ds Max with the standard animation biped skeleton is trivial. (And, honestly, cheaper than making tools that nobody uses!)

**Comment by Zatalyz** [comment]
Glad to hear it's so easy. So the issue will be resolved within the week. Good news for Ryzom!

**Comment by kaetemi** [comment]
If only you had the budget. :)

**Comment by kaetemi** [comment]
I don't do free labour. :)

**Comment by Zatalyz** [comment]
https://user-images.githubusercontent.com/10725489/152700959-c87942bf-162f-443e-a9d8-89f793823762.mp4

**Comment by kaetemi** [comment]
Um. Are you just fishing for trouble to talk bad about me? You're trying too hard. Have a little sense of humor, okay?

**Comment by kaetemi** [comment]
Don't assign me on this if you're just going to detract with the usual "there are no tools" excuses.

**Comment by kaetemi** [comment]
If you import the Ryzom character skeleton (rig) from 3ds Max to Blender, and make some quick sample animation with that, we can check if it'll work (or if we can make it work) and make the appropriate tools based on that. Any of the .max animation files will have the proper skeleton, and proper idle starting pose already.

In case that route doesn't give us correct data during export (flipped pivot points and so on), then we'll have to make a custom tool to transfer the 3ds Max skeleton to Blender. This may need a few more rounds of making a sample animation to confirm everything is good.

Potential issues are flipped pivot points, and mismatching animation controllers which may fail to blend. We cannot make any tools without having a few rounds of relevant sample assets to ensure everything will go flawlessly. It's possible that we'll also need to adjust the 3ds Max animation export to match things up. There are too many unknowns to put any timeline or deadline on this.

I can work on this, but I can only prioritize it if you're actually planning on contributing a significant amount of animations. If you don't have Max and need the skeleton exported for you, let me know and I'll export it and upload it here in a couple of standard formats.

**Comment by kaetemi** [comment]
Cleaning up stale issues.
