### ISSUE TITLE
Remove paypal link from README

### ISSUE THREAD

**Issue by ulukyn** [ryzom/ryzomcore#659]
We never asked to have a link to paypal in the README

I never gave permission to use my name, get money or be affliated to Paypal donate button

It's terrifying to see the liberties taken by the Ryzom Core team...

**Comment by kaetemi** [comment]
Your contributions are property of Winch Gate Ltd, and under your name on the Git repository. The PayPal links to the official Ryzom site's PayPal button.

At least we're not a dictatorship.
