### ISSUE TITLE
broken OGG file hangs client (on windows)

### ISSUE THREAD

**Issue by mlcdev** [ryzom/ryzomcore#661]
from client.log

2022/02/07 16:05:56 WRN 1638 ryzom_client_dev_r.exe audio_decoder_vorbis.cpp 183 NLSOUND::CAudioDecoderVorbis::getNextBytes : ov_read returned OV_EINVAL
2022/02/07 16:05:56 WRN 1638 ryzom_client_dev_r.exe audio_decoder_vorbis.cpp 183 NLSOUND::CAudioDecoderVorbis::getNextBytes : ov_read returned OV_EINVAL
2022/02/07 16:05:56 WRN 1638 ryzom_client_dev_r.exe audio_decoder_vorbis.cpp 183 NLSOUND::CAudioDecoderVorbis::getNextBytes : ov_read returned OV_EINVAL
2022/02/07 16:05:56 WRN 1638 ryzom_client_dev_r.exe audio_decoder_vorbis.cpp 183 NLSOUND::CAudioDecoderVorbis::getNextBytes : ov_read returned OV_EINVAL
2022/02/07 16:05:56 WRN 1638 ryzom_client_dev_r.exe audio_decoder_vorbis.cpp 183 NLSOUND::CAudioDecoderVorbis::getNextBytes : ov_read returned OV_EINVAL

the client keeps repeating this line and splits the client.log into hundreds of 5 mb log files, after a while windows reports the app is not responding. Occurs with the current Core4 supplied client binary.

**Comment by kaetemi** [comment]
Thanks, will fix ASAP.
