### ISSUE TITLE
ryzom lzma conflicts with linux lzma

### ISSUE THREAD

**Issue by LinuxDonald** [ryzom/ryzomcore#663]
Ryzoms lzma conflicts on install with linux lzma.
Maybe Ryzoms lzma could be renamed or adding support for linux lzma/Xz.

**Comment by kaetemi** [comment]
Library conflict or?

**Comment by LinuxDonald** [comment]
Yes both use the same name.

**Comment by nimetu** [comment]
I think I forgot to close this issue. Its fixed is d752c914
