### ISSUE TITLE
PushTarget in CNetworkConnection has a check that does not do anything

### ISSUE THREAD

**Issue by bierdosenhalter** [ryzom/ryzomcore#678]
assignment in the switch and after the switch
(also the slot assignment could be done in the action factory i guess)

```cpp
void	CNetworkConnection::pushTarget(TCLEntityId slot, LHSTATE::TLHState targetOrPickup )
{
	CActionTargetSlot *ats = (CActionTargetSlot*)CActionFactory::getInstance ()->create (INVALID_SLOT, ACTION_TARGET_SLOT_CODE);
	nlassert (ats != NULL);
	ats->Slot = slot;
	switch ( targetOrPickup ) // ensure the value is good for the FE
	{
		case LHSTATE::NONE: ats->TargetOrPickup = 0; break;
		case LHSTATE::LOOTABLE: ats->TargetOrPickup = 1; break;
		case LHSTATE::HARVESTABLE: ats->TargetOrPickup = 2; break;
	}

	ats->TargetOrPickup = (uint32)targetOrPickup;
	push(ats);
}
```

**Comment by kaetemi** [comment]
Ahah. Weird. Is this broken or dead code?

**Comment by bierdosenhalter** [comment]
i assume someone wanted to make sure targetOrPickup is a valid TLHState, but afterwards it is assigned anyway

**Comment by kaetemi** [comment]
It uses the same enum on the server, it's serialized as 2 bits, and there's also a value 3 now, so looks like dead code to me. Can safely remove that ugly switch with ugly numbers. :)

**Comment by kaetemi** [comment]
Feel free to send a PR.
