### ISSUE TITLE
Edit Tile Set Bottom Left Panel Clipping Issue

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#88]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/88) by Raster Ron (Bitbucket: [rasteron](https://bitbucket.org/rasteron), GitHub: [rasteron](https://github.com/rasteron)).**

----------------------------------------

Problem accessing the Edit Tile Set left panel in Tile Editor QT. The bottom part is clipped and my screen res is average 1366 x 768. Theres also a blank area taking up some space:

![Edit Tile Clipped](http://i.imgur.com/RECHZfJ.jpg)

Perhaps it could be like 3Ds Max's like panel where you can drag it to access the whole ui and add a maximize window button?

**Comment by ryzom-pipeline** [comment]
**Original comment by dfighter1985 (Bitbucket: [dfighter1985](https://bitbucket.org/dfighter1985), GitHub: [dfighter1985](https://github.com/dfighter1985)).**

----------------------------------------

Why is this assigned to me?
This isn't the Tile Editor plugin, this is the stand-alone Qt tool made by someone else.

**Comment by kaetemi** [comment]
Review Qt tools.
