### ISSUE TITLE
shard login function

### ISSUE THREAD

**Issue by ryzom-pipeline** [ryzom/ryzomcore#90]
**[Original report](https://bitbucket.org/ryzom/ryzomcore/issue/90) by Matthew Lagoe (Bitbucket: [botanic](https://bitbucket.org/botanic), GitHub: [botanic](https://github.com/botanic)).**

----------------------------------------

the shard uses the old r2_login rather then the new AMS login functions, should prolly fix that...

**Comment by kaetemi** [comment]
Review AMS.
